name: build-spm-metadata

inputs:
  module:
    description: The module name to run the task on if you have multiple kmp modules
    required: false
    type: string
  publishTask:
    description: 'The publish task to call if not kmmBridgePublish'
    default: 'kmmBridgePublish'
    required: false
    type: string
  netrcMachine:
    description: 'Netrc machine param'
    default: 'maven.pkg.github.com'
    required: false
    type: string
  jvmVersion:
    description: 'JVM Version to use. Will be passed to java-version parameter of setup-java'
    default: '11'
    required: false
    type: string
  runsOn:
    description: 'Host parameter to pass to runs-on'
    default: 'macos-12'
    required: false
    type: string
  token:
    description: access token
    default: ''
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Build SPM
      run: |
        jobs:
          kmmbridgepublish:
            runs-on: ${{ inputs.runsOn }}
            steps:
              - name: Checkout the repo
                uses: actions/checkout@v3

              - uses: extractions/netrc@v1
                with:
                  machine: ${{ inputs.netrcMachine }}
                  username: 'cirunner'
                  password: ${{ inputs.token }}

              - uses: actions/setup-java@v2
                with:
                  distribution: "adopt"
                  java-version: ${{ inputs.jvmVersion }}

              - name: Validate Gradle Wrapper
                uses: gradle/wrapper-validation-action@v1

              - name: Cache build tooling
                uses: actions/cache@v3
                with:
                  path: |
                    ~/.gradle/caches
                    ~/.konan
                  key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}

              - name: Build Main
                run: ./gradlew ${{ inputs.publishTask }} -PENABLE_PUBLISHING=true -PGITHUB_PUBLISH_TOKEN=${{ inputs.token }} -PGITHUB_REPO=SimonCfn/kmm-basic-sample --no-daemon --stacktrace
                env:
                  GRADLE_OPTS: '-Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"'

    - name: Run SPM Build Job
      run: |
        echo "Running SPM Build Job"
        echo "Module: ${{ inputs.module }}"
        echo "Publish Task: ${{ inputs.publishTask }}"
        echo "Netrc Machine: ${{ inputs.netrcMachine }}"
        echo "JVM Version: ${{ inputs.jvmVersion }}"
        echo "Runs On: ${{ inputs.runsOn }}"
        echo "Token: ${{ inputs.token }}"
