# Trigger on every tag creation
on:
  push:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-kmmbridge-publish:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.8
    with: 
      netrcMachine: touchlabartifactory.jfrog.io
    #- name: Setup Jfrog CLI
     # uses: jfrog/setup-jfrog-cli@v2
      #env:
       # JF_URL: https://ltlocaldev.jfrog.io
        #JF_USER: scanfin@listen-too.com
        #JF_PASSWORD: 123Jfrog!
        
    #- name: Jfrog CLI commands
     # run: 
      #  jf rt u ${PathFilesToUpload} ${JfReposotory}
        
  
