# Trigger on every tag creation
on:
  push:
    tags:
      - 'release-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build iOS framework
      id: buildPackage
      run: ./gradlew createSwiftPackage
    - name: Upload Swift Package directory
      uses: actions/upload-artifact@v2
      with:
        name: swiftpackage
        path: shared/swiftpackage
        retention-days: 1
    - name: Setup Jfrog CLI
      uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_URL: https://ltlocaldev.jfrog.io
        JF_USER: scanfin@listen-too.com
        JF_PASSWORD: 123Jfrog!
        
    - name: Jfrog CLI commands
      run: 
        jf rt ping
        jf rt bce
        jf rt bag
        jf rt bp
        
  
