# Trigger on every tag creation
on:
  push:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  kmmbridgepublish:
    concurrency: "kmmbridgepublish-SimonCfn/kmm-basic-sample"
    runs-on: 'macos-latest'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - uses: extractions/netrc@v1
        with:
          machine: 'maven.pkg.github.com'
          username: 'cirunner'
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache build tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: macos-latest-v4-${{ hashFiles('*.gradle.kts') }}

      - name: Build Main
        run: ./gradlew kmmBridgePublish -PENABLE_PUBLISHING=true -PGITHUB_PUBLISH_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_REPO=SimonCfn/kmm-basic-sample  --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
    #- name: Setup Jfrog CLI
     # uses: jfrog/setup-jfrog-cli@v2
      #env:
       # JF_URL: https://ltlocaldev.jfrog.io
        #JF_USER: scanfin@listen-too.com
        #JF_PASSWORD: 123Jfrog!
        
    #- name: Jfrog CLI commands
     # run: 
      #  jf rt u ${PathFilesToUpload} ${JfReposotory}
        
  
